# Generated by Django 4.2.11 on 2024-05-19 14:34

import localized_fields.fields.text_field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("astrowind_metadata", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="awmetadata",
            name="title_template",
            field=localized_fields.fields.text_field.LocalizedTextField(
                blank=True,
                default=dict,
                help_text=(
                    "Title template (default should be %s - {title}), used for default"
                    " site metadata."
                ),
                null=True,
                required=[],
            ),
        ),
    ]
