# Generated by Django 4.2.11 on 2024-06-20 17:22

from django.db import migrations

import headless_cms.fields.url_field


class Migration(migrations.Migration):

    dependencies = [
        (
            "astrowind_posts",
            "0002_awcategory_skip_translation_awpost_add_skip_translation",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="awpostimage",
            name="src_url",
            field=headless_cms.fields.url_field.LocalizedUrlField(
                blank=True, default=dict, null=True, required=[]
            ),
        ),
    ]
