# Generated by Django 4.2.20 on 2025-11-18 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("astrowind_posts", "0003_alter_awpostimage_src_url"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="awpost",
            new_name="awpost_publish_created_idx",
            old_fields=("publish_date", "created_date"),
        ),
    ]
