# Generated by Django 4.2.11 on 2024-04-24 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("astrowind_posts", "0007_remove_awpost_image_awpostimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="awpost",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posts",
                to="astrowind_posts.awpostimage",
            ),
        ),
    ]
