# Generated by Django 4.2.11 on 2024-04-26 16:17

import localized_fields.fields.text_field
import localized_fields.fields.uniqueslug_field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("astrowind_posts", "0008_awpost_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="awcategory",
            name="value",
            field=localized_fields.fields.uniqueslug_field.LocalizedUniqueSlugField(
                blank=True,
                include_time=False,
                null=True,
                populate_from="title",
                required=[],
                uniqueness=["en", "vi"],
            ),
        ),
        migrations.AddField(
            model_name="awposttag",
            name="title",
            field=localized_fields.fields.text_field.LocalizedTextField(
                blank=True, null=True, required=[]
            ),
        ),
        migrations.AlterField(
            model_name="awposttag",
            name="value",
            field=localized_fields.fields.uniqueslug_field.LocalizedUniqueSlugField(
                blank=True,
                include_time=False,
                null=True,
                populate_from="title",
                required=[],
                uniqueness=["en", "vi"],
            ),
        ),
    ]
