# Generated by Django 4.2.11 on 2024-04-26 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("astrowind_posts", "0009_awcategory_value_awposttag_title_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="awcategory",
            old_name="value",
            new_name="slug",
        ),
        migrations.RenameField(
            model_name="awposttag",
            old_name="value",
            new_name="slug",
        ),
    ]
