# Generated by Django 4.2.11 on 2024-04-29 17:04

from django.db import migrations

import headless_cms.fields.slug_field


class Migration(migrations.Migration):

    dependencies = [
        ("astrowind_posts", "0010_rename_value_awcategory_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="awcategory",
            name="slug",
            field=headless_cms.fields.slug_field.LocalizedUniqueNormalizedSlugField(
                blank=True,
                include_time=False,
                null=True,
                populate_from="title",
                required=[],
                uniqueness=["en", "vi"],
            ),
        ),
        migrations.AlterField(
            model_name="awposttag",
            name="slug",
            field=headless_cms.fields.slug_field.LocalizedUniqueNormalizedSlugField(
                blank=True,
                include_time=False,
                null=True,
                populate_from="title",
                required=[],
                uniqueness=["en", "vi"],
            ),
        ),
    ]
