# Generated by Django 4.2.11 on 2024-05-01 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("astrowind_posts", "0011_alter_awcategory_slug_alter_awposttag_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="awpost",
            name="image",
        ),
        migrations.DeleteModel(
            name="AWPostImage",
        ),
    ]
