# Generated by Django 4.2.11 on 2024-05-09 17:09

from django.db import migrations

import headless_cms.fields.slug_field


class Migration(migrations.Migration):

    dependencies = [
        ("astrowind_posts", "0013_awpostimage_awpost_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="awpost",
            name="slug",
            field=headless_cms.fields.slug_field.LocalizedUniqueNormalizedSlugField(
                blank=True,
                include_time=False,
                null=True,
                populate_from="title",
                required=[],
                uniqueness=["en", "vi"],
            ),
        ),
    ]
