# Generated by Django 4.2.11 on 2024-05-16 17:58

import django.db.models.deletion
from django.db import migrations, models

import headless_cms.fields.slug_field


class Migration(migrations.Migration):

    dependencies = [
        ("astrowind_posts", "0014_awpost_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="awcategory",
            name="slug",
            field=headless_cms.fields.slug_field.LocalizedUniqueNormalizedSlugField(
                blank=True,
                include_time=False,
                null=True,
                populate_from="title",
                required=[],
                uniqueness=["en", "vi", "zh", "ar"],
            ),
        ),
        migrations.AlterField(
            model_name="awpost",
            name="slug",
            field=headless_cms.fields.slug_field.LocalizedUniqueNormalizedSlugField(
                blank=True,
                include_time=False,
                null=True,
                populate_from="title",
                required=[],
                uniqueness=["en", "vi", "zh", "ar"],
            ),
        ),
        migrations.AlterField(
            model_name="awposttag",
            name="slug",
            field=headless_cms.fields.slug_field.LocalizedUniqueNormalizedSlugField(
                blank=True,
                include_time=False,
                null=True,
                populate_from="title",
                required=[],
                uniqueness=["en", "vi", "zh", "ar"],
            ),
        ),
        migrations.CreateModel(
            name="AWRelatedPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "related_post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_through",
                        to="astrowind_posts.awpost",
                    ),
                ),
                (
                    "source_post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_through",
                        to="astrowind_posts.awpost",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="awpost",
            name="related_posts",
            field=models.ManyToManyField(
                blank=True,
                through="astrowind_posts.AWRelatedPost",
                to="astrowind_posts.awpost",
            ),
        ),
    ]
