# Generated by Django 4.2.11 on 2024-05-18 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("astrowind_metadata", "0001_initial"),
        ("astrowind_posts", "0016_remove_awpost_metadata_delete_awpostmetadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="awpost",
            name="metadata",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="astrowind_metadata.awmetadata",
            ),
        ),
    ]
