# Generated by Django 4.2.11 on 2024-05-20 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("astrowind_posts", "0017_awpost_metadata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="awpost",
            name="updated_date",
            field=models.DateTimeField(),
        ),
    ]
