# Generated by Django 4.2.11 on 2024-04-06 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("astrowind_pages", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="awindexpage",
            name="contents",
        ),
    ]
