# Generated by Django 4.2.11 on 2024-04-15 16:43

import localized_fields.fields.text_field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("astrowind_pages", "0002_remove_awindexpage_contents"),
    ]

    operations = [
        migrations.AddField(
            model_name="awindexpage",
            name="title",
            field=localized_fields.fields.text_field.LocalizedTextField(
                blank=True, default=dict, null=True, required=[]
            ),
        ),
    ]
