# Generated by Django 4.2.11 on 2024-04-19 15:22

import django.db.models.deletion
import localized_fields.fields.text_field
import localized_fields.mixins
import psqlextra.manager.manager
from django.db import migrations, models

import headless_cms.admin
import headless_cms.mixins
import headless_cms.models


class Migration(migrations.Migration):

    dependencies = [
        ("reversion", "0002_add_index_on_version_for_content_type_and_db"),
        ("astrowind_widgets", "0026_alter_awcontentaction_variant_and_more"),
        ("astrowind_pages", "0004_awsite"),
    ]

    operations = [
        migrations.CreateModel(
            name="AWAboutFeature2Through",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["position"],
            },
            bases=(headless_cms.models.M2MSortedOrderThrough, models.Model),
        ),
        migrations.CreateModel(
            name="AWAboutFeature3Through",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["position"],
            },
            bases=(headless_cms.models.M2MSortedOrderThrough, models.Model),
        ),
        migrations.CreateModel(
            name="AWAboutPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    localized_fields.fields.text_field.LocalizedTextField(
                        blank=True, default=dict, null=True, required=[]
                    ),
                ),
                (
                    "feature2",
                    models.ManyToManyField(
                        blank=True,
                        through="astrowind_pages.AWAboutFeature2Through",
                        to="astrowind_widgets.awfeature2",
                    ),
                ),
                (
                    "feature3",
                    models.ManyToManyField(
                        blank=True,
                        through="astrowind_pages.AWAboutFeature3Through",
                        to="astrowind_widgets.awfeature3",
                    ),
                ),
                (
                    "hero",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="astrowind_widgets.awhero",
                    ),
                ),
                (
                    "published_version",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="reversion.version",
                    ),
                ),
                (
                    "stat",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="astrowind_widgets.awstat",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(localized_fields.mixins.AtomicSlugRetryMixin, models.Model),
            managers=[
                ("objects", psqlextra.manager.manager.PostgresManager()),
            ],
        ),
        migrations.CreateModel(
            name="AWAboutStep2Through",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "about_page",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="astrowind_pages.awaboutpage",
                    ),
                ),
                (
                    "step2",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="astrowind_widgets.awstep2",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
            },
            bases=(headless_cms.models.M2MSortedOrderThrough, models.Model),
        ),
        migrations.AddField(
            model_name="awaboutpage",
            name="step2",
            field=models.ManyToManyField(
                blank=True,
                through="astrowind_pages.AWAboutStep2Through",
                to="astrowind_widgets.awstep2",
            ),
        ),
        migrations.AddField(
            model_name="awaboutfeature3through",
            name="about_page",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="astrowind_pages.awaboutpage",
            ),
        ),
        migrations.AddField(
            model_name="awaboutfeature3through",
            name="feature3",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="astrowind_widgets.awfeature3",
            ),
        ),
        migrations.AddField(
            model_name="awaboutfeature2through",
            name="about_page",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="astrowind_pages.awaboutpage",
            ),
        ),
        migrations.AddField(
            model_name="awaboutfeature2through",
            name="feature2",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="astrowind_widgets.awfeature2",
            ),
        ),
    ]
