# Generated by Django 4.2.11 on 2024-04-19 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "astrowind_pages",
            "0005_awaboutfeature2through_awaboutfeature3through_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="awaboutpage",
            old_name="feature2",
            new_name="feature2s",
        ),
        migrations.RenameField(
            model_name="awaboutpage",
            old_name="feature3",
            new_name="feature3s",
        ),
        migrations.RenameField(
            model_name="awaboutpage",
            old_name="step2",
            new_name="step2s",
        ),
    ]
