# Generated by Django 4.2.11 on 2024-04-20 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "astrowind_widgets",
            "0027_remove_awpriceitem_pricing_awpriceitemthrough_and_more",
        ),
        ("astrowind_pages", "0007_awpricingpage"),
    ]

    operations = [
        migrations.AddField(
            model_name="awpricingpage",
            name="step",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="astrowind_widgets.awstep",
            ),
        ),
    ]
