# Generated by Django 4.2.11 on 2024-05-03 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("astrowind_widgets", "0042_alter_awbrandimagethrough_brand_and_more"),
        ("astrowind_pages", "0010_awindexpagecontentthrough_awindexpage_contents"),
    ]

    operations = [
        migrations.AlterField(
            model_name="awaboutfeature2through",
            name="about_page",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="astrowind_pages.awaboutpage",
            ),
        ),
        migrations.AlterField(
            model_name="awaboutfeature2through",
            name="feature2",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="astrowind_widgets.awfeature2",
            ),
        ),
        migrations.AlterField(
            model_name="awaboutfeature3through",
            name="about_page",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="astrowind_pages.awaboutpage",
            ),
        ),
        migrations.AlterField(
            model_name="awaboutfeature3through",
            name="feature3",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="astrowind_widgets.awfeature3",
            ),
        ),
        migrations.AlterField(
            model_name="awaboutstep2through",
            name="about_page",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="astrowind_pages.awaboutpage",
            ),
        ),
        migrations.AlterField(
            model_name="awaboutstep2through",
            name="step2",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="astrowind_widgets.awstep2",
            ),
        ),
        migrations.AlterField(
            model_name="awindexpagecontentthrough",
            name="content",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="astrowind_widgets.awcontent",
            ),
        ),
        migrations.AlterField(
            model_name="awindexpagecontentthrough",
            name="index_page",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="astrowind_pages.awindexpage",
            ),
        ),
    ]
