# Generated by Django 4.2.11 on 2024-05-17 16:53

import localized_fields.fields.char_field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("astrowind_pages", "0012_awpostpage"),
    ]

    operations = [
        migrations.AddField(
            model_name="awpostpage",
            name="blog_text",
            field=localized_fields.fields.char_field.LocalizedCharField(
                blank=True, default=dict, null=True, required=[]
            ),
        ),
    ]
