# Generated by Django 4.2.11 on 2024-05-17 17:26

import localized_fields.fields.char_field
import localized_fields.fields.text_field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("astrowind_pages", "0014_awsite_announcement"),
    ]

    operations = [
        migrations.AddField(
            model_name="awsite",
            name="philosophy",
            field=localized_fields.fields.text_field.LocalizedTextField(
                blank=True, default=dict, null=True, required=[]
            ),
        ),
        migrations.AddField(
            model_name="awsite",
            name="philosophy_text",
            field=localized_fields.fields.char_field.LocalizedCharField(
                blank=True, default=dict, null=True, required=[]
            ),
        ),
    ]
