# Generated by Django 4.2.11 on 2024-06-20 17:22

from django.db import migrations

import headless_cms.fields.url_field


class Migration(migrations.Migration):

    dependencies = [
        ("astrowind_widgets", "0002_awaction_add_skip_translation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="awimage",
            name="src_url",
            field=headless_cms.fields.url_field.LocalizedUrlField(
                blank=True, default=dict, null=True, required=[]
            ),
        ),
    ]
