# Generated by Django 4.2.11 on 2024-04-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("astrowind_widgets", "0002_alter_awfeature_columns_alter_awfeature2_columns"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="awcontent",
            options={"ordering": ["position"]},
        ),
        migrations.AddField(
            model_name="awcontent",
            name="position",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
