# Generated by Django 4.2.11 on 2024-04-05 17:49

import localized_fields.fields.text_field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("astrowind_widgets", "0003_alter_awcontent_options_awcontent_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="awcontent",
            name="content",
            field=localized_fields.fields.text_field.LocalizedTextField(
                blank=True, null=True, required=[]
            ),
        ),
    ]
