# Generated by Django 4.2.11 on 2024-04-05 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("astrowind_widgets", "0005_alter_awstatitem_options_awstatitem_position"),
    ]

    operations = [
        migrations.AlterField(
            model_name="awstatitem",
            name="icon",
            field=models.CharField(blank=True, default=""),
        ),
    ]
