# Generated by Django 4.2.11 on 2024-04-06 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("astrowind_widgets", "0006_alter_awstatitem_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="awfeature3",
            name="columns",
            field=models.IntegerField(default=0),
        ),
    ]
