# Generated by Django 4.2.11 on 2024-04-06 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("astrowind_widgets", "0007_alter_awfeature3_columns"),
    ]

    operations = [
        migrations.AddField(
            model_name="awcontent",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to=models.Q(("app_label", "astrowind_pages")),
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="awcontent",
            name="object_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
