# Generated by Django 4.2.11 on 2024-04-13 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("astrowind_widgets", "0010_awcontentaction_awctaaction_awheroaction_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="awbrandimage",
            options={"ordering": ["position"]},
        ),
        migrations.AlterModelOptions(
            name="awtestimonialitem",
            options={"ordering": ["position"]},
        ),
        migrations.AddField(
            model_name="awbrandimage",
            name="position",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="awtestimonialitem",
            name="position",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="awpriceitemaction",
            name="price_item",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="call_to_action",
                to="astrowind_widgets.awpriceitem",
            ),
        ),
    ]
