# Generated by Django 4.2.11 on 2024-04-13 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("astrowind_widgets", "0011_alter_awbrandimage_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="awcontentaction",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="awcontentaction",
            name="object_id",
        ),
        migrations.RemoveField(
            model_name="awctaaction",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="awctaaction",
            name="object_id",
        ),
        migrations.RemoveField(
            model_name="awheroaction",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="awheroaction",
            name="object_id",
        ),
        migrations.RemoveField(
            model_name="awherotextaction",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="awherotextaction",
            name="object_id",
        ),
        migrations.RemoveField(
            model_name="awherotextaction2",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="awherotextaction2",
            name="object_id",
        ),
        migrations.RemoveField(
            model_name="awpriceitemaction",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="awpriceitemaction",
            name="object_id",
        ),
        migrations.RemoveField(
            model_name="awstep2action",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="awstep2action",
            name="object_id",
        ),
        migrations.RemoveField(
            model_name="awtestimonialaction",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="awtestimonialaction",
            name="object_id",
        ),
    ]
