# Generated by Django 4.2.11 on 2024-04-15 16:20

from django.db import migrations

import headless_cms.fields.url_field


class Migration(migrations.Migration):

    dependencies = [
        ("astrowind_widgets", "0012_remove_awcontentaction_content_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="awcontentaction",
            name="href",
            field=headless_cms.fields.url_field.AutoLanguageUrlField(
                blank=True, default=""
            ),
        ),
        migrations.AlterField(
            model_name="awctaaction",
            name="href",
            field=headless_cms.fields.url_field.AutoLanguageUrlField(
                blank=True, default=""
            ),
        ),
        migrations.AlterField(
            model_name="awfooterlinkitem",
            name="href",
            field=headless_cms.fields.url_field.AutoLanguageUrlField(
                blank=True, default=""
            ),
        ),
        migrations.AlterField(
            model_name="awheroaction",
            name="href",
            field=headless_cms.fields.url_field.AutoLanguageUrlField(
                blank=True, default=""
            ),
        ),
        migrations.AlterField(
            model_name="awherotextaction",
            name="href",
            field=headless_cms.fields.url_field.AutoLanguageUrlField(
                blank=True, default=""
            ),
        ),
        migrations.AlterField(
            model_name="awherotextaction2",
            name="href",
            field=headless_cms.fields.url_field.AutoLanguageUrlField(
                blank=True, default=""
            ),
        ),
        migrations.AlterField(
            model_name="awpriceitemaction",
            name="href",
            field=headless_cms.fields.url_field.AutoLanguageUrlField(
                blank=True, default=""
            ),
        ),
        migrations.AlterField(
            model_name="awstep2action",
            name="href",
            field=headless_cms.fields.url_field.AutoLanguageUrlField(
                blank=True, default=""
            ),
        ),
        migrations.AlterField(
            model_name="awtestimonialaction",
            name="href",
            field=headless_cms.fields.url_field.AutoLanguageUrlField(
                blank=True, default=""
            ),
        ),
    ]
