# Generated by Django 4.2.11 on 2024-04-15 17:28

import localized_fields.fields.text_field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "astrowind_widgets",
            "0013_alter_awcontentaction_href_alter_awctaaction_href_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="awfooterlink",
            name="title",
            field=localized_fields.fields.text_field.LocalizedTextField(
                blank=True, default=dict, null=True, required=[]
            ),
        ),
    ]
