# Generated by Django 4.2.11 on 2024-04-15 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("astrowind_widgets", "0014_awfooterlink_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="awfooter",
            name="links",
            field=models.ManyToManyField(
                blank=True,
                related_name="links_footers",
                to="astrowind_widgets.awfooterlink",
            ),
        ),
        migrations.AlterField(
            model_name="awfooter",
            name="secondary_links",
            field=models.ManyToManyField(
                blank=True,
                related_name="secondary_links_footers",
                to="astrowind_widgets.awfooterlink",
            ),
        ),
        migrations.AlterField(
            model_name="awfooter",
            name="social_links",
            field=models.ManyToManyField(
                blank=True,
                related_name="social_links_footers",
                to="astrowind_widgets.awfooterlink",
            ),
        ),
    ]
