# Generated by Django 4.2.11 on 2024-04-15 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "astrowind_widgets",
            "0015_alter_awfooter_links_alter_awfooter_secondary_links_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="awfooterlinkitem",
            options={"ordering": ["position"]},
        ),
        migrations.RemoveField(
            model_name="awfooter",
            name="links",
        ),
        migrations.RemoveField(
            model_name="awfooter",
            name="secondary_links",
        ),
        migrations.RemoveField(
            model_name="awfooter",
            name="social_links",
        ),
        migrations.AddField(
            model_name="awfooterlinkitem",
            name="position",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
