# Generated by Django 4.2.11 on 2024-04-15 18:05

import django.db.models.deletion
import localized_fields.mixins
import psqlextra.manager.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reversion", "0002_add_index_on_version_for_content_type_and_db"),
        (
            "astrowind_widgets",
            "0016_alter_awfooterlinkitem_options_remove_awfooter_links_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="AWFooterSocialLinksThrough",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "footer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="astrowind_widgets.awfooter",
                    ),
                ),
                (
                    "footer_link",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="astrowind_widgets.awfooterlink",
                    ),
                ),
                (
                    "published_version",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="reversion.version",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
                "abstract": False,
            },
            bases=(localized_fields.mixins.AtomicSlugRetryMixin, models.Model),
            managers=[
                ("objects", psqlextra.manager.manager.PostgresManager()),
            ],
        ),
        migrations.CreateModel(
            name="AWFooterSecondaryLinksThrough",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "footer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="astrowind_widgets.awfooter",
                    ),
                ),
                (
                    "footer_link",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="astrowind_widgets.awfooterlink",
                    ),
                ),
                (
                    "published_version",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="reversion.version",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
                "abstract": False,
            },
            bases=(localized_fields.mixins.AtomicSlugRetryMixin, models.Model),
            managers=[
                ("objects", psqlextra.manager.manager.PostgresManager()),
            ],
        ),
        migrations.CreateModel(
            name="AWFooterLinksThrough",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "footer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="astrowind_widgets.awfooter",
                    ),
                ),
                (
                    "footer_link",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="astrowind_widgets.awfooterlink",
                    ),
                ),
                (
                    "published_version",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="reversion.version",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
                "abstract": False,
            },
            bases=(localized_fields.mixins.AtomicSlugRetryMixin, models.Model),
            managers=[
                ("objects", psqlextra.manager.manager.PostgresManager()),
            ],
        ),
        migrations.AddField(
            model_name="awfooter",
            name="links",
            field=models.ManyToManyField(
                blank=True,
                related_name="links_footers",
                through="astrowind_widgets.AWFooterLinksThrough",
                to="astrowind_widgets.awfooterlink",
            ),
        ),
        migrations.AddField(
            model_name="awfooter",
            name="secondary_links",
            field=models.ManyToManyField(
                blank=True,
                related_name="secondary_links_footers",
                through="astrowind_widgets.AWFooterSecondaryLinksThrough",
                to="astrowind_widgets.awfooterlink",
            ),
        ),
        migrations.AddField(
            model_name="awfooter",
            name="social_links",
            field=models.ManyToManyField(
                blank=True,
                related_name="social_links_footers",
                through="astrowind_widgets.AWFooterSocialLinksThrough",
                to="astrowind_widgets.awfooterlink",
            ),
        ),
    ]
