# Generated by Django 4.2.11 on 2024-04-15 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("astrowind_widgets", "0017_awfootersociallinksthrough_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="awfooterlinksthrough",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="awfootersecondarylinksthrough",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="awfootersociallinksthrough",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="awfooterlinksthrough",
            name="published_version",
        ),
        migrations.RemoveField(
            model_name="awfootersecondarylinksthrough",
            name="published_version",
        ),
        migrations.RemoveField(
            model_name="awfootersociallinksthrough",
            name="published_version",
        ),
    ]
