# Generated by Django 4.2.11 on 2024-04-15 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("astrowind_widgets", "0018_alter_awfooterlinksthrough_managers_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="awfooter",
            old_name="foot_name",
            new_name="foot_note",
        ),
    ]
