# Generated by Django 4.2.11 on 2024-04-16 07:22

import django.db.models.deletion
import localized_fields.fields.char_field
import localized_fields.mixins
import psqlextra.manager.manager
from django.db import migrations, models

import headless_cms.admin
import headless_cms.fields.url_field
import headless_cms.mixins
import headless_cms.models


class Migration(migrations.Migration):

    dependencies = [
        ("reversion", "0002_add_index_on_version_for_content_type_and_db"),
        ("astrowind_widgets", "0019_rename_foot_name_awfooter_foot_note"),
    ]

    operations = [
        migrations.CreateModel(
            name="AWHeader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(localized_fields.mixins.AtomicSlugRetryMixin, models.Model),
            managers=[
                ("objects", psqlextra.manager.manager.PostgresManager()),
            ],
        ),
        migrations.CreateModel(
            name="AWHeaderAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "variant",
                    models.CharField(
                        choices=[
                            ("primary", "Primary"),
                            ("secondary", "Secondary"),
                            ("tertiary", "Tertiary"),
                            ("link", "Link"),
                        ],
                        default="primary",
                    ),
                ),
                ("target", models.CharField(blank=True, default="")),
                (
                    "text",
                    localized_fields.fields.char_field.LocalizedCharField(
                        blank=True, null=True, required=[]
                    ),
                ),
                (
                    "href",
                    headless_cms.fields.url_field.AutoLanguageUrlField(
                        blank=True, default=""
                    ),
                ),
                ("icon", models.CharField(blank=True, default="")),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "published_version",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="reversion.version",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
                "abstract": False,
            },
            bases=(localized_fields.mixins.AtomicSlugRetryMixin, models.Model),
            managers=[
                ("objects", psqlextra.manager.manager.PostgresManager()),
            ],
        ),
        migrations.CreateModel(
            name="AWHeaderLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    localized_fields.fields.char_field.LocalizedCharField(
                        blank=True, null=True, required=[]
                    ),
                ),
                (
                    "href",
                    headless_cms.fields.url_field.AutoLanguageUrlField(
                        blank=True, default=""
                    ),
                ),
                (
                    "aria_label",
                    localized_fields.fields.char_field.LocalizedCharField(
                        blank=True, null=True, required=[]
                    ),
                ),
                ("icon", models.CharField(blank=True, default="")),
            ],
            options={
                "abstract": False,
            },
            bases=(localized_fields.mixins.AtomicSlugRetryMixin, models.Model),
            managers=[
                ("objects", psqlextra.manager.manager.PostgresManager()),
            ],
        ),
        migrations.CreateModel(
            name="AWHeaderLinkThrough",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "header",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="astrowind_widgets.awheader",
                    ),
                ),
                (
                    "header_link",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="astrowind_widgets.awheaderlink",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
            },
            bases=(headless_cms.models.M2MSortedOrderThrough, models.Model),
        ),
        migrations.CreateModel(
            name="AWHeaderLinkSelfThrough",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "child_link",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="link_children",
                        to="astrowind_widgets.awheaderlink",
                    ),
                ),
                (
                    "parent_link",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="link_parents",
                        to="astrowind_widgets.awheaderlink",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
            },
            bases=(headless_cms.models.M2MSortedOrderThrough, models.Model),
        ),
        migrations.AddField(
            model_name="awheaderlink",
            name="links",
            field=models.ManyToManyField(
                through="astrowind_widgets.AWHeaderLinkSelfThrough",
                to="astrowind_widgets.awheaderlink",
            ),
        ),
        migrations.AddField(
            model_name="awheaderlink",
            name="published_version",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="reversion.version",
            ),
        ),
        migrations.CreateModel(
            name="AWHeaderActionThrough",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "variant",
                    models.CharField(
                        choices=[
                            ("primary", "Primary"),
                            ("secondary", "Secondary"),
                            ("tertiary", "Tertiary"),
                            ("link", "Link"),
                        ],
                        default="primary",
                    ),
                ),
                ("target", models.CharField(blank=True, default="")),
                (
                    "text",
                    localized_fields.fields.char_field.LocalizedCharField(
                        blank=True, null=True, required=[]
                    ),
                ),
                (
                    "href",
                    headless_cms.fields.url_field.AutoLanguageUrlField(
                        blank=True, default=""
                    ),
                ),
                ("icon", models.CharField(blank=True, default="")),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "header",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="astrowind_widgets.awheader",
                    ),
                ),
                (
                    "header_action",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="astrowind_widgets.awheaderaction",
                    ),
                ),
                (
                    "published_version",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="reversion.version",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
            },
            bases=(localized_fields.mixins.AtomicSlugRetryMixin, models.Model),
            managers=[
                ("objects", psqlextra.manager.manager.PostgresManager()),
            ],
        ),
        migrations.AddField(
            model_name="awheader",
            name="actions",
            field=models.ManyToManyField(
                blank=True,
                related_name="actions_headers",
                through="astrowind_widgets.AWHeaderActionThrough",
                to="astrowind_widgets.awheaderaction",
            ),
        ),
        migrations.AddField(
            model_name="awheader",
            name="links",
            field=models.ManyToManyField(
                blank=True,
                related_name="links_headers",
                through="astrowind_widgets.AWHeaderLinkThrough",
                to="astrowind_widgets.awheaderlink",
            ),
        ),
        migrations.AddField(
            model_name="awheader",
            name="published_version",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="reversion.version",
            ),
        ),
    ]
