# Generated by Django 4.2.11 on 2024-04-16 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("astrowind_widgets", "0020_awheader_awheaderaction_awheaderlink_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="awheaderactionthrough",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="awheaderactionthrough",
            name="href",
        ),
        migrations.RemoveField(
            model_name="awheaderactionthrough",
            name="icon",
        ),
        migrations.RemoveField(
            model_name="awheaderactionthrough",
            name="published_version",
        ),
        migrations.RemoveField(
            model_name="awheaderactionthrough",
            name="target",
        ),
        migrations.RemoveField(
            model_name="awheaderactionthrough",
            name="text",
        ),
        migrations.RemoveField(
            model_name="awheaderactionthrough",
            name="variant",
        ),
    ]
