# Generated by Django 4.2.11 on 2024-04-16 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("astrowind_widgets", "0021_alter_awheaderactionthrough_managers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="awfooterlinkitem",
            name="footer_links",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET,
                related_name="links",
                to="astrowind_widgets.awfooterlink",
            ),
        ),
    ]
