# Generated by Django 4.2.11 on 2024-04-17 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "astrowind_widgets",
            "0023_awbrandimage_src_url_awcontentimage_src_url_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="awheroimage",
            name="hero",
        ),
        migrations.AddField(
            model_name="awhero",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="aw_heroes",
                to="astrowind_widgets.awheroimage",
            ),
        ),
    ]
