# Generated by Django 4.2.11 on 2024-04-19 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("astrowind_widgets", "0025_remove_awcontentaction_content_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="awcontentaction",
            name="variant",
            field=models.CharField(
                choices=[
                    ("primary", "Primary"),
                    ("secondary", "Secondary"),
                    ("tertiary", "Tertiary"),
                    ("link", "Link"),
                ],
                default="secondary",
            ),
        ),
        migrations.AlterField(
            model_name="awctaaction",
            name="variant",
            field=models.CharField(
                choices=[
                    ("primary", "Primary"),
                    ("secondary", "Secondary"),
                    ("tertiary", "Tertiary"),
                    ("link", "Link"),
                ],
                default="secondary",
            ),
        ),
        migrations.AlterField(
            model_name="awheaderaction",
            name="variant",
            field=models.CharField(
                choices=[
                    ("primary", "Primary"),
                    ("secondary", "Secondary"),
                    ("tertiary", "Tertiary"),
                    ("link", "Link"),
                ],
                default="secondary",
            ),
        ),
        migrations.AlterField(
            model_name="awheroaction",
            name="variant",
            field=models.CharField(
                choices=[
                    ("primary", "Primary"),
                    ("secondary", "Secondary"),
                    ("tertiary", "Tertiary"),
                    ("link", "Link"),
                ],
                default="secondary",
            ),
        ),
        migrations.AlterField(
            model_name="awherotextaction",
            name="variant",
            field=models.CharField(
                choices=[
                    ("primary", "Primary"),
                    ("secondary", "Secondary"),
                    ("tertiary", "Tertiary"),
                    ("link", "Link"),
                ],
                default="secondary",
            ),
        ),
        migrations.AlterField(
            model_name="awpriceitemaction",
            name="variant",
            field=models.CharField(
                choices=[
                    ("primary", "Primary"),
                    ("secondary", "Secondary"),
                    ("tertiary", "Tertiary"),
                    ("link", "Link"),
                ],
                default="secondary",
            ),
        ),
        migrations.AlterField(
            model_name="awstep2action",
            name="variant",
            field=models.CharField(
                choices=[
                    ("primary", "Primary"),
                    ("secondary", "Secondary"),
                    ("tertiary", "Tertiary"),
                    ("link", "Link"),
                ],
                default="secondary",
            ),
        ),
        migrations.AlterField(
            model_name="awtestimonialaction",
            name="variant",
            field=models.CharField(
                choices=[
                    ("primary", "Primary"),
                    ("secondary", "Secondary"),
                    ("tertiary", "Tertiary"),
                    ("link", "Link"),
                ],
                default="secondary",
            ),
        ),
    ]
