# Generated by Django 4.2.11 on 2024-04-21 15:54

import localized_fields.fields.char_field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "astrowind_widgets",
            "0027_remove_awpriceitem_pricing_awpriceitemthrough_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="awcontact",
            name="submit_url",
            field=localized_fields.fields.char_field.LocalizedCharField(
                blank=True, default=dict, null=True, required=[]
            ),
        ),
    ]
