# Generated by Django 4.2.11 on 2024-04-21 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("astrowind_widgets", "0028_awcontact_submit_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="awcontact",
            name="inputs",
        ),
        migrations.RemoveField(
            model_name="awtextarea",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="awtextarea",
            name="object_id",
        ),
        migrations.AlterField(
            model_name="awtextarea",
            name="name",
            field=models.CharField(default="message"),
        ),
    ]
