# Generated by Django 4.2.11 on 2024-04-21 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("astrowind_widgets", "0031_awdisclaimer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="awcontact",
            name="disclaimer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="astrowind_widgets.awdisclaimer",
            ),
        ),
    ]
