# Generated by Django 4.2.11 on 2024-04-21 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("astrowind_widgets", "0032_alter_awcontact_disclaimer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="awdisclaimer",
            name="autocomplete",
        ),
        migrations.RemoveField(
            model_name="awdisclaimer",
            name="name",
        ),
        migrations.RemoveField(
            model_name="awdisclaimer",
            name="placeholder",
        ),
        migrations.RemoveField(
            model_name="awdisclaimer",
            name="type",
        ),
    ]
