# Generated by Django 4.2.11 on 2024-05-01 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "astrowind_widgets",
            "0035_awimage_remove_awcontentimage_published_version_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="awcontent",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="aw_contents",
                to="astrowind_widgets.awimage",
            ),
        ),
        migrations.AddField(
            model_name="awhero",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="aw_heroes",
                to="astrowind_widgets.awimage",
            ),
        ),
        migrations.AddField(
            model_name="awstep",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="steps",
                to="astrowind_widgets.awimage",
            ),
        ),
        migrations.AddField(
            model_name="awtestimonialitem",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="testimonial_items",
                to="astrowind_widgets.awimage",
            ),
        ),
        migrations.CreateModel(
            name="AWBrandImageThrough",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "brand",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="astrowind_widgets.awbrand",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="astrowind_widgets.awimage",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="awbrand",
            name="images",
            field=models.ManyToManyField(
                blank=True,
                related_name="brands",
                through="astrowind_widgets.AWBrandImageThrough",
                to="astrowind_widgets.awimage",
            ),
        ),
    ]
