# Generated by Django 4.2.11 on 2024-05-01 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "astrowind_widgets",
            "0036_awcontent_image_awhero_image_awstep_image_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="awcontent",
            options={},
        ),
        migrations.RemoveField(
            model_name="awcontent",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="awcontent",
            name="object_id",
        ),
        migrations.RemoveField(
            model_name="awcontent",
            name="position",
        ),
    ]
