# Generated by Django 4.2.11 on 2024-05-01 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("astrowind_widgets", "0037_alter_awcontent_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="awstatitem",
            options={},
        ),
        migrations.RemoveField(
            model_name="awstatitem",
            name="position",
        ),
        migrations.RemoveField(
            model_name="awstatitem",
            name="stat_group",
        ),
        migrations.CreateModel(
            name="AWStatItemThrough",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "stat",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="astrowind_widgets.awstat",
                    ),
                ),
                (
                    "stat_item",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="astrowind_widgets.awstatitem",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="awstat",
            name="stats",
            field=models.ManyToManyField(
                blank=True,
                related_name="stat_groups",
                through="astrowind_widgets.AWStatItemThrough",
                to="astrowind_widgets.awstatitem",
            ),
        ),
    ]
