import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("astrowind_widgets", "0039_awaction_remove_awctaaction_cta_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="awcontent",
            name="call_to_action",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="aw_contents",
                to="astrowind_widgets.awaction",
            ),
        ),
        migrations.AddField(
            model_name="awherotext",
            name="call_to_action",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="aw_cta1_hero_texts",
                to="astrowind_widgets.awaction",
            ),
        ),
        migrations.AddField(
            model_name="awherotext",
            name="call_to_action2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="aw_cta2_hero_texts",
                to="astrowind_widgets.awaction",
            ),
        ),
        migrations.AddField(
            model_name="awpriceitem",
            name="call_to_action",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="price_items",
                to="astrowind_widgets.awaction",
            ),
        ),
        migrations.AddField(
            model_name="awstep2",
            name="call_to_action",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="step2s",
                to="astrowind_widgets.awaction",
            ),
        ),
        migrations.AddField(
            model_name="awtestimonial",
            name="call_to_action",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="testimonials",
                to="astrowind_widgets.awaction",
            ),
        ),
        migrations.CreateModel(
            name="AWHeroActionThrough",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "action",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="astrowind_widgets.awaction",
                    ),
                ),
                (
                    "hero",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="astrowind_widgets.awhero",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AWHeaderActionThrough",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "action",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="astrowind_widgets.awaction",
                    ),
                ),
                (
                    "header",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="astrowind_widgets.awheader",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AWCTAActionThrough",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "action",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="astrowind_widgets.awaction",
                    ),
                ),
                (
                    "cta",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="astrowind_widgets.awcalltoaction",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="awcalltoaction",
            name="actions",
            field=models.ManyToManyField(
                blank=True,
                related_name="ctas",
                through="astrowind_widgets.AWCTAActionThrough",
                to="astrowind_widgets.awaction",
            ),
        ),
        migrations.AddField(
            model_name="awheader",
            name="actions",
            field=models.ManyToManyField(
                blank=True,
                related_name="actions_headers",
                through="astrowind_widgets.AWHeaderActionThrough",
                to="astrowind_widgets.awaction",
            ),
        ),
        migrations.AddField(
            model_name="awhero",
            name="actions",
            field=models.ManyToManyField(
                blank=True,
                related_name="heroes",
                through="astrowind_widgets.AWHeroActionThrough",
                to="astrowind_widgets.awaction",
            ),
        ),
    ]
