# Generated by Django 4.2.11 on 2024-04-03 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["position"]},
        ),
        migrations.AddField(
            model_name="comment",
            name="position",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
