# Generated by Django 4.2.13 on 2024-06-17 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="skip_translation",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="articleimage",
            name="skip_translation",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="blog",
            name="skip_translation",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="category",
            name="skip_translation",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="domain",
            name="skip_translation",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="item",
            name="skip_translation",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="note",
            name="skip_translation",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="post",
            name="skip_translation",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="posttag",
            name="skip_translation",
            field=models.BooleanField(default=False),
        ),
    ]
